- src/index.ts
- src/types.ts
See https://github.com/NomicFoundation/hardhat/blob/231f7c47637821970dffa3d496c370afd7858bf2/packages/hardhat-core/src/types/config.ts#L183
`hardhatConfigNetworks()` output currently can't be used in hardhat directly, I need to typecast the chain IDs (otherwise 2.0.0 seems 100% backwards compatible)
> Change chain ID type to number for HardhatConfigNetwork

- README.md
- src/hardhat-config.ts
- src/hardhat.ts
- src/index.ts
- src/types.ts
- src/utils/strings.test.ts
- src/utils/strings.ts
I refactored the code around hardhat to address https://github.com/api3dao/chains/issues/15
```ts
// Old
hardhatConfigNetworks();
hardhatEtherscan();
// New
hardhatConfig.networks();
hardhatConfig.etherscan();
``` 
As part of this change, I also updated the expected API key environment variable names from `ETHERSCAN_API_KEY_${chain.alias}` to `ETHERSCAN_API_KEY_${toUpperSnakeCase(chain.alias)}`. This means that environment variables should be changed as follows:
```sh
ETHERSCAN_API_KEY_arbitrum-goerli-testnet=1234
ETHERSCAN_API_KEY_ARBITRUM_GOERLI_TESTNET=1234
```
Mixing snake & kebab case felt weird to me, but I'm happy to revert if you prefer the former.
The result of this should be that you no longer need the boilerplate code mentioned in the linked issue. It should be as simple as: …
> Update Hardhat config to remove the need for boilerplate code

- src/utils/strings.test.ts
- src/utils/strings.ts
Closes https://github.com/api3dao/chains/issues/46
> Fix env variable names

- package.json
- scripts/calculate-average-block-times.ts
- scripts/ping-providers.ts
I need to add new testnets and these were blocking me
> Improve scripts

- README.md
- src/hardhat-config.ts
1. Adds the ability to override URL values when generating Hardhat networks. These optional env variables have the form of `HARDHAT_HTTP_RPC_URL_${toUpperSnakeCase(chain)}` and are also included in the list of environment variables from `getEnvVariableNames()`.
Resolves: https://github.com/api3dao/chains/issues/51
@bbenligiray I'm not sure I understand [this comment](https://github.com/api3dao/chains/issues/51#issuecomment-1635845801) though. This repo no longer does any `.env`/`.env.example` generation.
> Add optional env variable overrides for network RPC URLs

- .github/workflows/continuous-build.yml
- scripts/generate-chains.ts
Apologies I missed that upgrading to Prettier v3 broke the `generate-chains` script. I've adjusted the script to be async now that the exposed Prettier functions return promises.
> Fix generate-chains script to work with Prettier v3

- src/hardhat-config.ts
I distinctly remember testing https://github.com/api3dao/chains/pull/53 so I have no idea how this happened. Maybe I entered the environment variable manually and only tested that it overrides the default but not this function.
> Fix the environment variable names for hardhat RPC URLs

- chains/gnosis-testnet.json
- src/generated/chains.ts
They've updated it but the API still doesn't work :/
> Fix gnosis testnet explorer urls

- chains/kava-testnet.json
- src/generated/chains.ts
This one is an actual fix. Oddly enough kavascan.com takes you to a blockscout instance.
> Fix kava explorer urls

- .github/workflows/check-providers.yml
- chains/boba-avalanche.json
- package.json
- scripts/calculate-average-block-times.ts
- scripts/ping-providers.ts
- src/generated/chains.ts
- yarn.lock
1. Rework the `ping-providers` script to be able to notify Slack when given `SLACK_TOKEN` and `SLACK_CHANNEL` environment variables
2. Add a new workflow that runs the `providers:ping` script on a cron schedule (once a day at 12:00) and on pull request.
3. Replace `ethers` with `viem`. I strongly prefer the latter for lots of reasons that I'm happy to expand on, but let me know if you have a problem with this.
btw, the `ping-providers` script failed significantly more than it succeeded while I was testing this. Some chains (godwoken, boba-avalanche and boba-ethereum) often report a block timestamp that was > 5 minutes in the past 😅 
Addresses: https://github.com/api3dao/chains/issues/70
> Run providers:ping on a cron schedule and notify Slack

- chains/zksync-goerli-testnet.json
- chains/zksync.json
- src/generated/chains.ts
- src/hardhat-config.test.ts
- src/hardhat-config.ts
- src/types.ts
Adds a new optional `hardhatConfigOverrides` object for each chain. This object can an optional `networks` object (leaving space for future customisations later). If a chain has network overrides, these get merged with the existing results from calling `hardhatConfig.networks()`. I've added specific tests for the chains with these overrides (`zksync` and `zksync-goerli-testnet`).
Closes: https://github.com/api3dao/chains/issues/55
> Add zkSync (and testnet) hardhat config network overrides

- README.md
- src/hardhat-config.ts
- src/viem-config.test.ts
- src/viem-config.ts
Currently Hardhat allows for [overriding the `url` field](https://github.com/api3dao/chains/blob/2a4cd589ab14b61c2ed2b3bd69d10617f42d6c5e/src/hardhat-config.ts#L74) of each network if a specific environment variable is found (`HARDHAT_HTTP_RPC_URL_${toUpperSnakeCase(chain.alias)}`)
This PR implements a similar feature for `viemConfig.chains()` to maintain some level of parity. I first had it replace the `rpcUrls.public` and `rpcUrls.default` values if the env variable exists, but then figured we could just keep those exposed and add a new field if the new env variable is found (`API3_CHAINS_HTTP_RPC_URL_${toUpperSnakeCase(chain.alias)}`).
Let me know what you think
> Viem RPC URL environment variable support

- scripts/ping-providers.ts
- src/types.ts
Allows addition of chains that don't support dAPIs. Closes #153.
I tested this by:
1. changing the `default` `rpcUrl` to nonsense for `arbitrum-goerli-testnet.json`, running `yarn generate:chains` and confirming that an error was returned when running `export CHAIN=arbitrum-goerli-testnet; yarn providers:ping`
2. then I added `"skipProviderCheck": true`, reran `yarn generate:chains`, and the ping command passed
> Add optional skipProviderCheck field to chain schema

- chains/blast-sepolia-testnet.json
- src/generated/chains.ts
Addded `blast-sepolia-testnet`. We recently deployed the Testnet Random Numbers QRNG Provider there.
[Blast Sepolia Testnet](https://testnet.blastscan.io/)
[AirnodeRrpV0.sol](https://testnet.blastscan.io/address/0xD223DfDCb888CA1539bb3459a83c543A1608F038)
> Add Blast Sepolia Testnet

- chains/ethereum.json
- src/generated/chains.ts
The current `default` provider for `ethereum` occasionally encounters reliability issues. This PR suggests replacing it with a more dependable alternative.
> Update `default` provider for `ethereum`

- chains/lightlink-goerli-testnet.json
- chains/lightlink.json
- src/generated/chains.ts
I was looking for a chain to test my deployment scripts on and noticed that this is wrong
> Fix Lightlink block explorer API key flag

- .github/workflows/refresh-block-time.yml
Closes #165. Tested in my fork: here is the [action run](https://github.com/dcroote/chains/actions/runs/7896924464/job/21551656185) and the [resulting PR](https://github.com/dcroote/chains/pull/1). Note for testing on my fork I had a manual trigger that I removed for this PR. Also note there isn't caching since [GitHub evicts cache entries older than 7 days](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy) and since this is planned for monthly, caching won't help.
> Add GitHub Action to refresh block times

- chains/blast.json
- src/generated/chains.ts
Reblok deployed RPC node for the chain `blast`. 
For your visibility @aquarat @vponline: `proxy.reblok.io/blast/reblok` endpoint has been deployed so you can use it for the collector applications
> Add provider `reblok` for the chain `blast`

- chains/mantle-sepolia-testnet.json
- src/generated/chains.ts
As a note, I typically add super new chains and `providers:time` fails because the chain doesn't have [400000 blocks](https://github.com/api3dao/chains/blob/main/scripts/calculate-average-block-times.ts#L6) yet, so I reduce that number manually to run the script and end up getting a weird block time such as the 2000 here
> Add mantle-sepolia-testnet

- package.json
- yarn.lock
When I cloned this and accidentally installed with pnpm instead of yarn I received the following warning which I thought wouldn't hurt to apply:
```
WARN  deprecated @types/prettier@3.0.0: This is a stub types definition. prettier provides its own type definitions, so you do not need this installed.
```
> Remove dep @types/prettier@3.0.0

- chains/blast-sepolia-testnet.json
- src/generated/chains.ts
This chain is actively maintained. So it's better to not skip provider check for it.
> Do not skip provider check for blast-sepolia-testnet

- chains/oev-network-agg-sepolia-testnet.json
- src/generated/chains.ts
This one is a bit annoying. I wanted to keep the `l2name-l1name-testnet` convention in the alias (for stuff line `.endsWith('-testnet')`), but Gateway used `oev-network-sepolia-testnet-agg` as the chain name on their end. I guess as soon as we switch to this testnet, we can remove the old one and update the name/alias of this one to not have "agg" in it.
> Add OEV Network AggLayer testnet

- .changeset/nervous-books-travel.md
- .prettierignore
- chains/blast-sepolia-testnet.json
- src/generated/chains.ts
Closes #213. The URL is per the [docs here](https://docs.blastscan.io/v/sepolia-blastscan). This also now matches the non-testnet blast config:
https://github.com/api3dao/chains/blob/21239109e005aab02f931bee53c5c10c6f8f2cf9/chains/blast.json#L7-L12
Second commit adds a changeset and also adds the .changeset directory to `.prettierignore` which was necessary because prettier was unhappy about the changeset having default double quotes instead of single quotes around the package name
> Update blast sepolia api and browser urls

- .github/workflows/release.yml
The last [Release action](https://github.com/api3dao/chains/actions/runs/8603532202/job/23575638355#step:7:8) had the error:
```
Run git checkout main
error: pathspec 'main' did not match any file(s) known to git
```
which strangely didn't happen before, but is plausibly explained by the Release workflow being triggered by the `production` branch and having only that branch present. Indeed during the Action:
```
Fetching the repository
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +5938ec727ebf355e41338701fcd8bf0f3feca6d2:refs/remotes/origin/production
From https://github.com/api3dao/chains
* [new ref]         5938ec727ebf355e41338701fcd8bf0f3feca6d2 -> origin/production
Determining the checkout info
Checking out the ref
/usr/bin/git …
```
> Add fetch-depth: 0 to release clone step

- .changeset/bright-experts-juggle.md
- chains/polygon-testnet.json
- src/generated/chains.ts
This chain has been deprecated, so it can be disregarded. Additionally, `skipProviderCheck` is being utilized by the app `rpc-watcher`. Consequently, pricing logs will no longer be collected. This change is acceptable, as we are no longer accepting new subscriptions on this chain.
Related to https://github.com/api3dao/tasks/issues/1021.
> Skip provider check for polygon-testnet

- .changeset/five-bulldogs-bake.md
- chains/sei-testnet.json
- chains/sei.json
- chains/taiko.json
- src/generated/chains.ts
Closes #330 
**sei - [bridge](https://app.sei.io/bridge) - [docs](https://www.docs.sei.io/dev-gas)**
---
sei contract verification api is not available ATM but contracts are already verified on `sei-testnet` process. That is being said `sei` uses the same block explorer for both testnet and mainnet chains. Thus to avoid external link errors `sei-testnet` block explorer replaced with an alternative one.
[OwnableCallForwarder](https://seitrace.com/address/0xef455205966486F52f7951ba4C3517239B036835)
[Api3ServerV1](https://seitrace.com/address/0x3ee097B82E270d82f829e5742cC16B7686247Ff2)
[DataFeedProxy](https://seitrace.com/address/0x9Cf90E5B9292a82B214925f0b707779E0aFa0F74)
[DapiProxy](https://seitrace.com/address/0x73Eb8A060e52efC2513861282Ff62B9182daC5c6) …
> Add chains for `CSUR-2024-05-28`

- .changeset/nice-needles-yell.md
- chains/taiko.json
- src/generated/chains.ts
Rushing this so that it's in the next Dint deployment
> Temporarily change the default Taiko RPC until the official one is fixed

- .changeset/seven-donkeys-explode.md
- chains/astar.json
- chains/bob.json
- chains/bsquared.json
- chains/core.json
- chains/kava.json
- chains/kroma.json
- chains/mantle.json
- chains/merlin.json
- chains/metis.json
- chains/mode.json
- chains/opbnb.json
- chains/taiko.json
- chains/x-layer.json
- src/generated/chains.ts
I revisited RPC provider supports for the recently integrated chains. For this end, new subscriptions have been bought for `1rpc`, `ankr` and `rockx`.
> Add providers for several chains

- .changeset/tall-avocados-suffer.md
- chains/blast-sepolia-testnet.json
- src/generated/chains.ts
As convention says, `-testnet` should be lower-cased.
> Update name of blast-sepolia-testnet

- .changeset/popular-poems-refuse.md
- chains/taiko.json
- src/generated/chains.ts
- Provider maintained by Taiko Labs has been added.
- Provider `blockpi` has been removed because it returns gas price more than 1000x (eth_gasPrice) and causes overpriced transactions. One can see [here](https://monitor.reblok.io/d/GsfMlsc4k/rpc-watcher?orgId=1&var-chain=taiko&var-provider=All&var-published=All&from=1717876318573&to=1717962718573&viewPanel=46).
> Update providers for taiko

- .changeset/brown-seas-enjoy.md
- chains/core.json
- chains/kroma.json
- chains/mode.json
- src/generated/chains.ts
This is technically unreliable provider with high response latency and lots of down-time. It will be better to not have.
> Remove provider 1rpc from the existing chains

- .changeset/tasty-jars-punch.md
- chains/ethereum.json
- src/generated/chains.ts
Response time of the current default provider is on higher side. So I'm proposing to switch better alternative.
> Update default provider for ethereum

- .github/workflows/continuous-build.yml
Closes #374. The alternative would be to move the changeset check to a separate file, but I don't feel that's necessary
> Do not check for changesets on push to main

- .changeset/clean-windows-move.md
- chains/manta.json
- chains/zircuit.json
- src/generated/chains.ts
Closes #405 
`public` RPC for `manta` renamed to `default` as its mandatory to poses a provider called `default`
> Remove inconsistent providers from manta and zircuit

- .github/workflows/release.yml
Similar to: https://github.com/api3dao/oev-auctioneer/pull/453
Part of: https://github.com/api3dao/tasks/issues/1374
> Document workflow secrets

- .changeset/empty-pandas-sip.md
- chains/sonic-testnet.json
- src/generated/chains.ts
See: https://github.com/api3dao/tasks/issues/1395, [slack](https://api3workspace.slack.com/archives/C075C5780HJ/p1724744875672289)
This PR adds following chain:
* sonic-testnet
This chain does not have a working contract verification module, yet.
> Add sonic-testnet for CSUR

- .changeset/fuzzy-foxes-serve.md
- chains/sonic-testnet.json
- src/generated/chains.ts
Closes #436 based on https://docs.soniclabs.com/sonic/testnet/getting-started
> fix: update sonic-testnet RPC and browser URLs

- .changeset/spotty-foxes-buy.md
- chains/astar-sepolia-testnet.json
- chains/astar.json
- src/generated/chains.ts
Closes https://github.com/api3dao/chains/issues/445
It is listed on [docs](https://docs.gelato.network/web3-services/web3-functions/supported-networks) but you cannot create a task using Gelato interface for Astar zkEVM chains
> Remove broken RPC providers

- .github/workflows/continuous-build.yml
Excluding `dependabot` from `require-changeset` condition like `renovate`.
> Exclude dependabot from require-changeset

- .changeset/forty-vans-speak.md
- chains/conflux-testnet.json
- chains/ethereum-sepolia-testnet.json
- chains/fraxtal-holesky-testnet.json
- chains/gnosis.json
- chains/kava-testnet.json
- chains/kava.json
- chains/taiko-holesky-testnet.json
- chains/taiko.json
- chains/x-layer-sepolia-testnet.json
- chains/x-layer.json
- src/generated/chains.ts
Closes #488 
This PR fixes following issues:
* ethereum-sepolia-testnet
- Remove [inconsistent rpc](https://status.sepolia.org) url
* fraxtal-holesky-testnet
- Set api key required to true
* gnosis
- Change hardhatEtherscanAlias
* kava
- [Update api url](https://docs.kava.io/docs/ethereum/contract_verification/#via-hardhat-verification-plugin)
* kava-testnet
- [Update api url](https://docs.kava.io/docs/ethereum/contract_verification/#via-hardhat-verification-plugin)
* taiko
- Swap default rpc url with public
* taiko-holesky-testnet
- Replace block explorer with a new one
* x-layer
- Update [api url](https://www.okx.com/xlayer/docs/developer/verify-a-smart-contract/verify-with-hardhat)
* x-layer-sepolia-testnet
- Update [api url](https://www.okx.com/xlayer/docs/developer/verify-a-smart-cont …
> Fix outdated chain properties

- .changeset/grumpy-experts-collect.md
- chains/fantom-testnet.json
- src/generated/chains.ts
* Fantom testnet rpc url is not working properly. This pr updates the default rpc with working now.
> Fix fantom-testnet default rpc

- .changeset/friendly-pots-repair.md
- chains/sonic-testnet.json
- src/generated/chains.ts
Closes https://github.com/api3dao/chains/issues/509
This is a major release and contains following changes:
* New chain id and url update for `sonic-testnet`
This chain does not support contract verification, so there is no block explorer api available
> Csur 2024-12-04

- .changeset/kind-lions-cross.md
- chains/linea.json
- src/generated/chains.ts
QuickNode requires an additional purchase for the Linea endpoint, and it cannot be used with the multi-chain endpoint. To maintain multi-chain functionality, I suggest removing it.
> Replace quicknode with publicnode for linea

- .changeset/honest-plants-tan.md
- chains/polygon.json
- src/generated/chains.ts
Context: ankr returnes cached data on `eth_call` endpoint
Related to #527 
See [thread](https://api3workspace.slack.com/archives/C05RMQJ3X2L/p1734049355849149)
Also [example](https://api3workspace.slack.com/archives/C05RMQJ3X2L/p1734034235172479), [example](https://api3workspace.slack.com/archives/C05RMQJ3X2L/p1733926236032789), [example](https://api3workspace.slack.com/archives/C05RMQJ3X2L/p1733849032329649), [example](https://api3workspace.slack.com/archives/C05RMQJ3X2L/p1733849032329649)
> Remove ankr from polygon

- .changeset/empty-trainers-do.md
- chains/berachain-testnet.json
- src/generated/chains.ts
Related to #534 
* Publicnode rpc is working more reliable than current default rpc
* berachain-testnet `default` rpc is swapped with `publicnode` rpc. 
* Default rpc is not removed entirely as it shows signs of recovery and will be remain monitored
> Change default rpc for berachain-testnet

- .changeset/plenty-hats-breathe.md
- chains/astar-sepolia-testnet.json
- chains/ink.json
- chains/sonic-testnet.json
- chains/sonic.json
- src/generated/chains.ts
Closes #554 #557 #556
* Add `quicknode` to `ink`
* Update broser and RPC URLs for `sonic` and `sonic-testnet`
* Check `skipProviderCheck` flag to true for `astar-sepolia-testnet`
Contracts are verified on `sonic` and `sonic-testnet`
> Update chain configurations

- .changeset/little-rats-tap.md
- chains/kroma.json
- src/generated/chains.ts
Closes #561 
> Kroma has changed its block explorer as shown in [docs](https://docs.kroma.network/users/block-explorer).
> 
> New block explorer: https://kroscan.io/
> [API](https://kroscan.io/documentation/recipes/hardhat-verification): https://api.routescan.io/v2/network/mainnet/evm/255/etherscan
> Update outdated kroma block explorer
