- chains/linea-goerli-testnet.json
- src/generated/chains.ts
> Fix linea testnet api key requirement

- chains/optimism-sepolia-testnet.json
- src/generated/chains.ts
Inspired by https://github.com/api3dao/airnode/issues/1938
> Add optimism-sepolia-testnet

- chains/arbitrum-goerli-testnet.json
- chains/metis-goerli-testnet.json
- chains/optimism-goerli-testnet.json
- chains/optimism-sepolia-testnet.json
- chains/polygon-zkevm-goerli-testnet.json
- chains/zksync-goerli-testnet.json
- src/generated/chains.ts
- tsconfig.json
I was meaning to fix the Optimism Goerli testnet name but then I noticed that the naming was irregular across a number of chains
> Fix testnet names

- chains/base-sepolia-testnet.json
- src/generated/chains.ts
> Add base-sepolia-testnet

- package.json
Similar to: https://github.com/api3dao/signed-api/pull/265
> Add repository and sideEffects fields to package.json

- src/types.test.ts
- src/types.ts
> Validate chainSchema symbol is <= 6 characters

- .changeset/nervous-books-travel.md
- CHANGELOG.md
- package.json
Edit: I think this has to be a merge commit (rather than rebase / squash to keep the commit sha, which is associated with the npm release)
Edit 2: I'm wondering if the v4.16.1 tag may need to be moved to the release commit 4dcfd8e after this...
This PR (`production` back to `main`) would have been automatically created by the Action (see below), but didn't this round because re-running the release Action resulted in the if conditional not being satisfied. I'm pretty sure next release it should all go smoothly. Note you may want to change the `--reviewer` after this @andreogle 
https://github.com/api3dao/chains/blob/a9baef5ef17e207daa76967871a581f9d23ed1ad/.github/workflows/release.yml#L59-L63
> Merge production into main

- .changeset/eight-ducks-lay.md
- chains/lightlink-sepolia-testnet.json
- src/generated/chains.ts
> Fix chain name `lightlink-sepolia-testnet`

- .changeset/stupid-knives-taste.md
- chains/inevm-sepolia-testnet.json
- chains/inevm-testnet.json
- chains/inevm.json
- chains/kroma-sepolia-testnet.json
- chains/kroma.json
- src/generated/chains.ts
Closes https://github.com/api3dao/chains/issues/266
Deployments shown below are mock deployments and demonstration of contract verification process.
**kroma** [docs](https://docs.kroma.network/user-guide/cofigure-your-wallet)
---
[OwnableCallForwarder](https://kromascan.com/address/0xef455205966486F52f7951ba4C3517239B036835)
[AccessControlRegistry](https://kromascan.com/address/0xcD7Df573B0F0bb4F2f8dFFF6650cDe8C77431730)
[Api3ServerV1](https://kromascan.com/address/0x3ee097B82E270d82f829e5742cC16B7686247Ff2)
[DataFeedProxy](https://kromascan.com/address/0x9Cf90E5B9292a82B214925f0b707779E0aFa0F74)
[DapiProxy](https://kromascan.com/address/0x73Eb8A060e52efC2513861282Ff62B9182daC5c6)
[DataFeedProxyWithOev](https://kromascan.com/address/0x18d6F2b16729F2B06eBa584B3Cd9B30771Ceb5c7) …
> Add new chains for `CSUR-2024-05-02`

- .changeset/metal-penguins-share.md
- scripts/ping-providers.ts
Closes #282 (see issue for description and rationale)
> Fix ping-providers validateLatestBlock error handling

- .changeset/fair-ladybugs-shout.md
- chains/metis-sepolia-testnet.json
- src/generated/chains.ts
Closes #287 
See https://api3workspace.slack.com/archives/C06QY4X81PG/p1714995220135539?thread_ts=1714994816.459049&cid=C06QY4X81PG
> Fix symbol name for Metis Sepolia testnet

- .changeset/early-cows-repair.md
- chains/apechain-testnet.json
- chains/astar-zkevm-sepolia-testnet.json
- chains/astar-zkevm.json
- chains/core-chain.json
- chains/core.json
- chains/immutable-zkevm-sepolia-testnet.json
- src/generated/chains.ts
Closes #307 
**immutable-zkevm-sepolia-testnet - [docs](https://docs.immutable.com/docs/zkevm/overview/)**
---
[OwnableCallForwarder](https://explorer.testnet.immutable.com/address/0xef455205966486F52f7951ba4C3517239B036835)
[Api3ServerV1](https://explorer.testnet.immutable.com/address/0x3ee097B82E270d82f829e5742cC16B7686247Ff2)
[DataFeedProxy](https://explorer.testnet.immutable.com/address/0x9Cf90E5B9292a82B214925f0b707779E0aFa0F74)
[DapiProxy](https://explorer.testnet.immutable.com/address/0x73Eb8A060e52efC2513861282Ff62B9182daC5c6)
[DataFeedProxyWithOev](https://explorer.testnet.immutable.com/address/0x18d6F2b16729F2B06eBa584B3Cd9B30771Ceb5c7)
[DapiProxyWithOev](https://explorer.testnet.immutable.com/address/0x62AbEfcFD9451364E4Eb8bC7aEF9540378e3Eb3c) …
> Add new chains `CSUR-2024-05-16`

- .changeset/clean-squids-kneel.md
- chains/polygon-sepolia-testnet.json
- chains/x-layer-sepolia-testnet.json
- chains/x-layer.json
- chains/zircuit-sepolia-testnet.json
- src/generated/chains.ts
See https://github.com/api3dao/data-feeds/issues/219
> Update explorer URLs

- .changeset/curvy-laws-serve.md
- chains/canto-testnet.json
- chains/canto.json
- chains/meld-testnet.json
- chains/meld.json
- chains/metal.json
- src/generated/chains.ts
Closes #320 
**canto - [bridge](https://canto.io/bridge) - [docs](https://docs.canto.io/user-guides/connecting-to-canto)**
---
This chain does not allow legacy transaction, thus deterministic deployment is not available
[OwnableCallForwarder](https://www.oklink.com/canto/address/0xd5CaB12D597670e098322eD27D32659F59592349/contract)
[Api3ServerV1](https://www.oklink.com/canto/address/0x8FD1EFcB673D1438CB153783AcE6b65b7eBa1A60/contract)
[DataFeedProxy](https://www.oklink.com/canto/address/0x169101eF0fC57725cbe64d68e6454b4dFb1AC84a/contract)
[DapiProxy](https://www.oklink.com/canto/address/0xe10EEF809D831718d42432453d13A82c48291374/contract)
[DataFeedProxyWithOev](https://www.oklink.com/canto/address/0xcE14D281d4127c3DddBE527d41F386F861188343/contract) …
> Add new chains Canto, Canto Testnet, Meld, Meld Testnet, Metal L2

- .changeset/pink-mice-fry.md
- chains/polygon.json
- src/generated/chains.ts
> Update default provider of polygon

- .changeset/weak-apes-tell.md
- chains/lukso-testnet.json
- src/generated/chains.ts
> Update symbol for Lukso testnet chain

- .changeset/dull-stingrays-visit.md
- README.md
> Remove hyperlink on the badge for `download per week

- .changeset/brave-flies-flow.md
- chains/zircuit.json
- src/generated/chains.ts
Closes https://github.com/api3dao/tasks/issues/1280
> Add zircuit chain 

- .changeset/lemon-rats-exist.md
- package.json
- pnpm-lock.yaml
Related to https://github.com/api3dao/data-feeds/issues/613
> Initiate release

- .changeset/funny-crabs-doubt.md
- chains/zircuit.json
- src/generated/chains.ts
> Fix zircuit block explorer

- .changeset/gold-zebras-explain.md
- chains/sei-testnet.json
- src/generated/chains.ts
Closes https://github.com/api3dao/tasks/issues/1327
> Update `sei-testnet` deployment

- .changeset/yellow-donkeys-sing.md
- chains/camp-sepolia-testnet.json
- src/generated/chains.ts
Check https://github.com/api3dao/data-feeds/issues/762
> Add `camp-sepolia-testnet`

- .changeset/cold-pugs-shave.md
- chains/zircuit.json
- src/generated/chains.ts
> Update RPC urls for `zircuit` chain

- .changeset/wise-pets-cheat.md
- chains/canto.json
- src/generated/chains.ts
Its default provider has been failing for a while.
> Update default provider for canto

- .changeset/polite-icons-dress.md
- chains/soneium-sepolia-testnet.json
- src/generated/chains.ts
Related to https://github.com/api3dao/tasks/issues/1414, [slack](https://api3workspace.slack.com/archives/C075C5780HJ/p1725523342966769)
> Add Soneium testnet chain

- .changeset/cyan-shirts-approve.md
- package.json
- pnpm-lock.yaml
- scripts/generate-chains.ts
Related to https://github.com/api3dao/tasks/issues/1414
Add following chain:
* soneium-sepolia-testnet
> Add new chain for CSUR

- .changeset/late-shirts-jog.md
- chains/zircuit-sepolia-testnet.json
- chains/zircuit.json
- src/generated/chains.ts
Closes #438 
See [mainnet](https://docs.zircuit.com/dev-tools/block-explorer) and [testnet](https://docs.zircuit.com/testnet/block-explorer) documentation
> Update Zircuit explorer URLs for testnet and mainnet

- .changeset/eleven-phones-repair.md
- chains/polygon-sepolia-testnet.json
- chains/polygon.json
- src/generated/chains.ts
Closes https://github.com/api3dao/chains/issues/443
The change has been marked as `major` 
WDYT?
> Update MATIC symbol to POL

- .changeset/shaggy-actors-train.md
- chains/oev-network.json
- src/generated/chains.ts
Closes #456 
Relates to https://github.com/api3dao/oev-dashboard/issues/191
> Swap out block explorer for OEV Network

- .changeset/fresh-foxes-carry.md
- .eslintignore
- .eslintrc.js
- package.json
- pnpm-lock.yaml
- scripts/generate-chains.ts
- scripts/ping-providers.ts
- scripts/validate-chains.ts
- src/generated/chains.ts
- src/hardhat-config.test.ts
- src/hardhat-config.ts
- src/types.test.ts
- src/types.ts
- src/utils/arrays.test.ts
- src/utils/strings.test.ts
- src/utils/strings.ts
- src/validations/deep-equal.test.ts
- src/viem-config.test.ts
- src/viem-config.ts
- tsconfig.eslint.json
> Add api3/eslint-plugin-commons and apply lints

- .changeset/slow-boxes-add.md
- chains/unichain-sepolia-testnet.json
- src/generated/chains.ts
Closes https://github.com/api3dao/tasks/issues/1460
See https://api3workspace.slack.com/archives/C075C5780HJ/p1728593736262189
> Add new chains for `CSUR 2024-10-16`

- .changeset/cool-peas-tan.md
- chains/world-sepolia-testnet.json
- chains/world.json
- src/generated/chains.ts
Closes https://github.com/api3dao/tasks/issues/1471
See https://api3workspace.slack.com/archives/C075C5780HJ/p1729206468644269
Named as World Chain and World Chain testnet as there is also Worldcoin
> Csur 2024-10-23

- .changeset/pretty-schools-breathe.md
- chains/apechain.json
- src/generated/chains.ts
Closes https://github.com/api3dao/tasks/issues/1478
See https://api3workspace.slack.com/archives/C075C5780HJ/p1729602209317109
> Csur 2024 10 30

- .changeset/green-dolphins-jam.md
- chains/atleta-sepolia-testnet.json
- chains/atleta-testnet.json
- src/generated/chains.ts
Related to https://github.com/api3dao/data-feeds/issues/1130
[Docs](https://blockchain-sports.gitbook.io/atleta-network/testnet/olympia-information)
> CSUR-2024-11-06

- .changeset/khaki-countries-speak.md
- chains/ink-sepolia-testnet.json
- src/generated/chains.ts
Closes https://github.com/api3dao/tasks/issues/1503
- ink-sepolia-testnet [docs](https://docs.inkonchain.com/quick-start/get-connected) - [bridge](https://docs.inkonchain.com/quick-start/faucets#bridging-funds-to-ink-sepolia) - [faucet](https://docs.inkonchain.com/quick-start/faucets)
> Csur 2024-11-15

- .changeset/grumpy-keys-play.md
- chains/sonic.json
- src/generated/chains.ts
As part of https://github.com/api3dao/data-feeds/issues/1882 https://github.com/api3dao/tasks/issues/1547
> Csur 2024-12-11

- .changeset/smart-grapes-repair.md
- chains/hashkey-sepolia-testnet.json
- chains/hashkey-testnet.json
- src/generated/chains.ts
Related to https://github.com/api3dao/tasks/issues/1558, https://github.com/api3dao/data-feeds/issues/1937
See also https://github.com/api3dao/chains/issues/529
Note: This chain uses `op-stack`
> Add hashkey-testnet

- .changeset/brave-boxes-walk.md
- chains/sonic.json
- src/generated/chains.ts
Sonic has only one provider.
To be safe alchemy has been added to providers.
> Add additional RPCs to sonic

- .changeset/smooth-balloons-remember.md
- chains/ink.json
- src/generated/chains.ts
Related to https://github.com/api3dao/data-feeds/issues/1968
Closes https://github.com/api3dao/tasks/issues/1563
This PR adds `ink` chain
Gas fee calculation type: `op-stack`
> Csur 2024-12-19

- .changeset/chatty-badgers-rhyme.md
- chains/mantle-sepolia-testnet.json
- chains/mantle.json
- src/generated/chains.ts
> Update mantle and mantle-sepolia-testnet block explorer

- .changeset/five-melons-melt.md
- chains/soneium.json
- src/generated/chains.ts
See slack [thread](https://api3workspace.slack.com/archives/C075C5780HJ/p1736880148546179)
Closes https://github.com/api3dao/tasks/issues/1589#top
Fee calculation type: `op-stack`
> Csur 2025-01-16

- .changeset/tall-walls-tan.md
- chains/berachain-testnet.json
- src/generated/chains.ts
> Update default provider for berachain-testnet

- .changeset/cyan-monkeys-draw.md
- chains/unichain.json
- src/generated/chains.ts
Related to https://github.com/api3dao/tasks/issues/1626, https://github.com/api3dao/data-feeds/issues/2370
This PR adds `unichain`
- Unichain is using op-stack
> Csur 2025-02-12
